/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;

public class App {
    private String nome;
    private double[] notas;

    public App(String nome, double nota1, double nota2, double nota3) {
        this.nome = nome;
        this.notas = new double[]{nota1, nota2, nota3};
    }

    public double calcularMedia() {
        double soma = 0;
        for (double nota : notas) {
            soma += nota;
        }
        return soma / notas.length;
    }

    public String getSituacao() {
        double media = calcularMedia();
        if (media >= 7.0) {
            return "Aprovado";
        } else if (media >= 5.0) {
            return "Recuperação";
        } else {
            return "Reprovado";
        }
    }

    public String exibirBoletim() {
        return String.format(
                "Aluno: %s\nNotas: %s\nMedia: %.2f\nSituação: %s",
                nome,
                Arrays.toString(notas),
                calcularMedia(),
                getSituacao()
        );
    }


    // Getters (opcionalmente, para uso em testes)
    public String getNome() {
        return nome;
    }

    public double[] getNotas() {
        return notas;
    }
}
